include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    comment_references: true
    prefer_final_fields: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_relative_imports: true
    directives_ordering: true
    sort_child_properties_last: true
    sort_pub_dependencies: true