name: speedup
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  expandable_page_view: ^1.0.14
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: IBMPlexSansBold
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf

    - family: IBMPlexSansBoldItalic
      fonts:
        - asset: assets/fonts/IBMPlexSans-BoldItalic.ttf

    - family: IBMPlexSansExtraLight
      fonts:
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf

    - family: IBMPlexSansExtraLightItalic
      fonts:
        - asset: assets/fonts/IBMPlexSans-ExtraLightItalic.ttf

    - family: IBMPlexSansItalic
      fonts:
        - asset: assets/fonts/IBMPlexSans-Italic.ttf

    - family: IBMPlexSansLight
      fonts:
        - asset: assets/fonts/IBMPlexSans-Light.ttf

    - family: IBMPlexSansLightItalic
      fonts:
        - asset: assets/fonts/IBMPlexSans-LightItalic.ttf

    - family: IBMPlexSansMedium
      fonts:
        - asset: assets/fonts/IBMPlexSans-Medium.ttf

    - family: IBMPlexSansMediumItalic
      fonts:
        - asset: assets/fonts/IBMPlexSans-MediumItalic.ttf

    - family: IBMPlexSansRegular
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf

    - family: IBMPlexSansSemiBold
      fonts:
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf

    - family: IBMPlexSansSemiBoldItalic
      fonts:
        - asset: assets/fonts/IBMPlexSans-SemiBoldItalic.ttf

    - family: IBMPlexSansThin
      fonts:
        - asset: assets/fonts/IBMPlexSans-Thin.ttf

    - family: IBMPlexSansThinItalic
      fonts:
        - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf
